[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gitrelay"
version = "0.0.1"
authors = [
  { name="Luís Gomes", email="luismsgomes@gmail.com" },
]
description = "A tool to synchronize git repos with smart scheduling and systemd integration."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic",
    "typer",
    "rich",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
]

[project.urls]
"Homepage" = "https://github.com/luismsgomes/gitrelay"
"Bug Tracker" = "https://github.com/luismsgomes/gitrelay/issues"

[project.scripts]
gitrelay = "gitrelay.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = [
    "E", # pycodestyle errors
    "F", # Pyflakes (unused imports, etc.)
    "I", # isort (import sorting)
]
ignore = []
